const assert = require("node:assert/strict");
const { game, context, dispatchKey, dispatchKeyUp, element } = require("./check-game.cjs");
game.resetRun(0);
const flight = JSON.stringify({ player: game.player, time: game.runTime(), lives: game.lives(), seals: game.sealCount() });
assert.equal(game.enterHarbor("missing"), false);
assert.equal(game.enterHarbor("rihtim"), true);
assert.equal(game.state(), "exploring");
assert.equal(element("#hud").hidden, true);
assert.equal(element("#social-hud").hidden, false);
game.keys.add("KeyD");
for (let i = 0; i < 120; i++) game.updateSocial(1/120);
assert.ok(game.player.x > 300);
assert.equal(game.player.y, 512);
assert.equal(game.runTime(), 0);
game.keys.clear();
game.player.x = 310;
assert.equal(game.openConversation(), true);
assert.equal(game.conversation().person.id, "emine");
const startX = game.player.x;
game.keys.add("KeyD");
for (let i = 0; i < 60; i++) game.updateSocial(1/120);
assert.equal(game.player.x, startX, "Conversation must stop walking");
assert.equal(game.courier.input.talking, true);
game.chooseConversation(0);
assert.equal(game.conversation().node, "rota");
game.chooseConversation(99); assert.equal(game.conversation().node, "rota");
game.closeConversation();
assert.equal(game.conversation(), null);
assert.equal(game.openConversation("hasan"), false, "Only nearby people can be addressed");
game.toggleMap(); assert.equal(game.state(), "map");
const mapPose = JSON.stringify({ player: game.player, pose: game.courier.snapshot(), time: game.visualTime() });
game.frame(1000); game.frame(1050);
assert.equal(JSON.stringify({ player: game.player, pose: game.courier.snapshot(), time: game.visualTime() }), mapPose);
game.travelToDock("fener"); assert.equal(game.socialDock().id, "fener");
assert.equal(game.state(), "exploring");
game.keys.add("KeyD");
for (let i = 0; i < 2000; i++) game.updateSocial(1/120);
assert.equal(game.player.x, context.HarborWorld.docks[3].right - 20, "Walkers cannot leave safe floor");
assert.equal(game.lives(), 3);
assert.equal(game.runTime(), 0);
assert.equal(game.sealCount(), 0);
game.leaveHarbor();
assert.equal(game.state(), "playing");
assert.equal(JSON.stringify({ player: game.player, time: game.runTime(), lives: game.lives(), seals: game.sealCount() }), flight,
  "Exploration must restore the suspended route without score/time/item changes");
game.takeHit("water");
const rescued = JSON.stringify(game.player);
game.enterHarbor("rihtim"); game.leaveHarbor();
assert.equal(game.recoveryReady(), true); assert.equal(JSON.stringify(game.player), rescued);
game.enterHarbor("vinc");
game.pauseGame(); assert.equal(game.state(), "paused");
element("#restart-button").click(); assert.equal(game.state(), "exploring");
assert.equal(game.socialDock().id, "vinc");
game.pauseGame();
game.resumeGame(); assert.equal(game.state(), "exploring");
dispatchKey("KeyD"); game.updateSocial(0.05); dispatchKeyUp("KeyD");
game.player.x = 5720; dispatchKey("KeyE");
assert.equal(game.conversation().person.id, "okan");
dispatchKey("Escape"); assert.equal(game.conversation(), null);
assert.equal(game.state(), "exploring");
game.leaveHarbor();
game.resetRun(-1); game.finishRun(true);
game.enterHarbor("fener"); game.leaveHarbor();
assert.equal(game.state(), "won", "Post-run visit returns to saved results");

const heldState = () => JSON.stringify({player:game.player,ring:game.tetherAnchor()?.id,length:game.ropeLength(),wear:game.tetherTime(),time:game.runTime(),stats:game.stats()});
function heldFlight(visit) {
  game.resetRun(0); game.beginTether();
  Object.assign(game.player,{x:532,y:500,vx:200,vy:180});
  if(visit) {
    const held=heldState(); game.toggleMap(); dispatchKeyUp('Space'); game.travelToDock('vinc');
    game.toggleMap(); game.travelToDock('fener'); game.leaveHarbor();
    assert.equal(heldState(),held,'Travel must restore the entire held rope, velocity, wear and route');
  }
  for(let i=0;i<42;i++) game.update(1/120);
  return heldState();
}
const control=heldFlight(false);
assert.equal(heldFlight(true),control,'Visiting docks must preserve the subsequent physical flight');
assert.equal(game.stats().hits,0,'Harbor return must not turn a safe swing into a fall');
game.pauseGame(); dispatchKeyUp('Space'); assert.ok(game.tetherAnchor(),'Paused key release preserves the rope'); game.resumeGame();
const restoredRing=game.tetherAnchor();
const mouse={pointerType:'mouse',button:0,pointerId:44,currentTarget:{setPointerCapture(){}}};
for(const listener of element('#game').listeners.get('pointerdown')) listener(mouse);
for(const listener of element('#game').listeners.get('pointerup')) listener(mouse);
assert.equal(game.tetherAnchor(),null,'A fresh mouse hold/release works on a preserved rope');
assert.equal(restoredRing.visited,true);
game.resetRun(0); Object.assign(game.player,{x:4140,y:485,vx:0,vy:0}); game.beginTether(); game.updateSpecialRing(.6);
const wear=game.tetherTime(); game.enterHarbor('vinc'); game.leaveHarbor();
assert.equal(game.tetherTime(),wear,'Fragile-ring wear survives a harbor visit');
game.updateSpecialRing(.96); assert.equal(game.tetherAnchor(),null);
console.log("Harbor checks passed: actual walking, proximity conversation, branching, map, pause, dock travel, safe floor, route restoration and record isolation.");
